
resolver: lts-16.16

packages:
- BookSamples/CH03/Section3p1
- BookSamples/CH03/Section3p2
- BookSamples/CH03/Section3p3
- BookSamples/CH04/Section4p1
- BookSamples/CH04/Section4p2
- BookSamples/CH05/Section5p1
- BookSamples/CH05/Section5p2x1
- BookSamples/CH05/Section5p2x2
- BookSamples/CH05/Section5p3
- BookSamples/CH06/Section6p1
